---
title: "Reporte COVID - 19: Perú"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    social: ["menu"]
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(lubridate)
library(data.table)
library(leaflet)
library(leaflet.extras)
library(rvest)
library(sf)
library(glue)
library(highcharter)
library(COVID19)

## Configuración de ggplot2

theme_set(theme_minimal() + 
              theme(text = element_text(family = "Trebuchet MS"), 
                    plot.caption = element_text(face = "bold", 
                                                size = 20), 
                    axis.title = element_text(face = "bold"), 
                    plot.title = element_text(face = "bold")))

## Configuración de HighCharts

lang <- getOption("highcharter.lang")
lang$decimalPoint <- "."
lang$months <- c("Enero", "Febrero", "Marzo", "Abril", 
                 "Mayo", "Junio", "Julio", "Agosto", 
                 "Septiembre", "Octubre", "Noviembre", "Diciembre")
lang$shortMonths <- substring(lang$months, 1, 3)
lang$weekdays <- c("Domingo", "Lunes", "Martes", "Miércoles", 
                   "Jueves", "Viernes", "Sábado")

options(highcharter.lang = lang)
```

```{r global-functions, include=FALSE}
# library(httr)
# library(curl)
# library(stringr)
# library(jsonlite)
# 
# authentication_token <- function(tenant, client_id, client_secret){
#   h <- new_handle()
#   handle_setform(h, 
#                  "grant_type" = "client_credentials", 
#                  "resource" = "https://management.core.windows.net/", 
#                  "client_id" = client_id, 
#                  "client_secret" = client_secret
#   )
#   path <- str_interp("https://login.windows.net/${tenant}/oauth2/token")
#   req <- curl_fetch_memory(path, handle = h)
#   res <- fromJSON(rawToChar(req$content))
#   return(paste("Bearer", res$access_token))
# }
# 
# load_data <- function(datalake, path, auth_token, sep = "\u0001", colClasses = NA){
#   file_path <- str_interp("https://${datalake}.azuredatalakestore.net/webhdfs/v1/${path}?op=OPEN&read=true")
#   r <- httr::GET(file_path, add_headers(Authorization = auth_token))
#   return(read.csv(textConnection(content(r, "text", encoding = "UTF-8")), 
#                   check.names = FALSE, 
#                   sep = sep, 
#                   colClasses = colClasses) %>% dplyr::as_tibble())
# }
# 
# upload_data <- function(dataset, datalake, path, auth_token){
#   write.csv(dataset, textConnection("filecontent", "w"))
#   file_path <- str_interp("https://${datalake}.azuredatalakestore.net/webhdfs/v1/${path}?op=CREATE&overwrite=true&write=true")
#   httr::PUT(file_path, 
#             body = filecontent, 
#             add_headers(Authorization = auth_token, 
#                         "Transfer-Encoding" = "chunked"))
#   return("The file is uploaded")
# }
# 
# datalake_name <- "adslhatunanalytics"
# token <- authentication_token(tenant = "75382e44-1b6a-4a9e-a262-c2df3919df29",
#                               client_id = "abea3eec-d439-43fe-b4c2-37b73de745b0",
#                               client_secret = "q1_NIq8Ei975hN~.9HwkxEj~HdFwOP0B~O")
```


```{r global, include=FALSE}
dfFallecidos <- fread("https://cloud.minsa.gob.pe/s/Md37cjXmjT9qYSa/download",
                      na.strings = c("", "NULL"), encoding = "UTF-8") %>%
  as_tibble() %>%
  # mutate_if(is.character, ~ str_conv(., "latin1")) %>%
  mutate_if(is.character, str_to_title) %>%
  mutate_at("FECHA_FALLECIMIENTO", ymd)
  # mutate_at("FECHA_FALLECIMIENTO", ~as.Date(., tryFormats = "%d%m%Y"))

dfPositivos <- fread("https://cloud.minsa.gob.pe/s/Y8w3wHsEdYQSZRp/download",
                     na.strings = c("", "NULL"), encoding = "UTF-8") %>%
  as_tibble() %>%
  # mutate_if(is.character, ~ str_conv(., "latin1")) %>%
  mutate_if(is.character, str_to_title) %>%
  mutate_at("FECHA_RESULTADO", ymd)

dfVacunados <- fread("https://cloud.minsa.gob.pe/s/ZgXoXqK2KLjRLxD/download", 
                     na.strings = c("", "NULL"), encoding = "UTF-8") %>% 
  as_tibble() %>% 
  mutate_if(is.character, str_to_title) %>% 
  mutate_at(vars(FECHA_VACUNACION), ymd)

# pagCoronavirus <- read_html("https://es.wikipedia.org/wiki/Anexo:Estad%C3%ADsticas_de_la_pandemia_de_COVID-19_en_Per%C3%BA")

dfPeruCovid <- covid19("peru") %>% 
  ungroup() %>% 
  as_tibble() %>% 
  mutate_if(is.numeric, ~replace_na(., 0))

dfCovidNacional <- dfPeruCovid %>% 
  ungroup() %>% 
  filter(confirmed != 0) %>% 
  select(date:icu, -vent) %>% 
  mutate(recovered = case_when(date == "2020-07-27" & recovered == 2727547 ~ 272547, 
                               date == "2020-10-02" & recovered == 690528 ~ 695645, 
                               date == "2021-02-24" & recovered == 0 ~ 1204050, 
                               TRUE ~ recovered)) %>% 
  rename("fecha" = "date",
         "pruebas_acum" = "tests", 
         "confirmados_acum" = "confirmed", 
         "recuperados_acum" = "recovered", 
         "muertes_acum" = "deaths", 
         "hospitalizados_acum" = "hosp", 
         "uci_acum" = "icu") %>% 
  mutate(activos_acum = confirmados_acum - recuperados_acum - muertes_acum, 
         confirmados_nuevos = confirmados_acum - lag(confirmados_acum, default = 0), 
         recuperados_nuevos = recuperados_acum - lag(recuperados_acum, default = 0), 
         muertes_nuevos = muertes_acum - lag(muertes_acum, default = 0), 
         pruebas_nuevos = pruebas_acum - lag(pruebas_acum, default = 0), 
         uci_nuevos = uci_acum - lag(uci_acum, default = 0), 
         hospitalizados_nuevos = hospitalizados_acum - lag(hospitalizados_acum, 
                                                           default = 0), 
         activos_nuevos = activos_acum - lag(activos_acum, default = 0))

while(tail(dfCovidNacional$confirmados_acum, 2)[1] == tail(dfCovidNacional$confirmados_acum, 2)[2] | tail(dfCovidNacional$recuperados_acum, 1) == 0){
  dfCovidNacional <- dfCovidNacional %>% 
    slice(-n())
}
  
  
# dfConfirmadosDepartamentos <- pagCoronavirus %>% 
#   html_nodes('.wikitable') %>% 
#   html_table(fill = T) %>% 
#   tibble('Tablas' = .) %>% 
#   .[1,] %>% 
#   unnest() %>% 
#   # slice(-1) %>% 
#   janitor::row_to_names(1) %>% 
#   janitor::clean_names() %>% 
#   select(-contains("poblacion")) %>% 
#   rename_at(vars(-contains("departamentos")), ~c("confirmados", "casos_prev", 
#                                                  "fallecidos", "muertes_prev", 
#                                                  "letalidad", 
#                                                  "dir_muertes_cant", 
#                                                  "dir_muertes_prev")) %>% 
#   select(-contains(c("dir", "prev"))) %>% 
#   slice(-1) %>% 
#   rename_all(str_to_upper) %>% 
#   filter(!str_detect(DEPARTAMENTOS, 'Total|Fuente')) %>% 
#   mutate_at(c("CONFIRMADOS", "FALLECIDOS"), ~ str_replace_all(., "\\s", "") %>% 
#               as.numeric()) %>% 
#   mutate_at('LETALIDAD', ~substring(., 1, nchar(.)-2) %>% 
#               str_replace_all(',', '.') %>% 
#               as.numeric()) %>% 
#   mutate(
#     DEPARTAMENTOS = 
#       stringi::stri_trans_general(DEPARTAMENTOS, "Latin-ASCII") %>% 
#       str_to_upper()
#     ) %>% 
#   rename(DEPARTAMENTO = DEPARTAMENTOS)

# tbCoronavirus <- pagCoronavirus %>% 
#   html_nodes('.wikitable') %>% 
#   html_table(fill = T) %>% 
#   tibble('Tablas' = .) %>% 
#   .[1,] %>% 
#   unnest() %>% 
#   janitor::row_to_names(1) %>% 
#   # slice(-1) %>%
#   janitor::clean_names() %>% 
#   select(-contains(c("poblacion", "ref", "_n_"))) %>% 
#   select(-contains(c("dir", "prev", "total", "hab", "acum_"))) %>%
#   rename_at(vars(-contains(c("departamento", "prev"))), ~c("confirmados", 
#                                                  "fallecidos")) %>% 
#   # slice(-1) %>% 
#   rename_all(str_to_upper) %>% 
#   rename(DEPARTAMENTO = DEPARTAMENTOO_PROVINCIAS_AUTONOMAS) %>% 
#   filter(!str_detect(DEPARTAMENTO, 'Total|Fuente')) %>% 
#   mutate_at(c("CONFIRMADOS", "FALLECIDOS"), ~ str_replace_all(., "\\s", "") %>% 
#               as.numeric()) %>% 
#   # mutate_at('LETALIDAD', ~substring(., 1, nchar(.)-2) %>% 
#   #             str_replace_all(',', '.') %>% 
#   #             as.numeric()) %>% 
#   mutate(
#     DEPARTAMENTO = 
#       stringi::stri_trans_general(DEPARTAMENTO, "Latin-ASCII") %>% 
#       str_to_upper()
#     ) #%>% 
  # rename(DEPARTAMENTO = DEPARTAMENTOS)

meses <- c("Enero", "Febrero", "Marzo", "Abril", 
           "Mayo", "Junio", "Julio", "Agosto", "Septiembre", 
           "Octubre", "Noviembre", "Diciembre")
# dfPeru <- st_read("../DASHBOARDS/data/DEPARTAMENTOS.shp")
# dfPeru <- rename(dfPeru, DEPARTAMENTO = DEPARTAMEN)

if(require("rnaturalearth")){
  library(rnaturalearth)
}else{
  devtools::install_github("ropensci/rnaturalearth")
  library(rnaturalearth)
}

if(require("rnaturalearthhires")){
  library(rnaturalearthhires)
}else{
  devtools::install_github("ropensci/rnaturalearthhires")
  library(rnaturalearthhires)
}

if(require("rgeos")){
  library(rgeos)
}else{
  install.packages("rgeos")
  library(rgeos)
}


# library(rnaturalearth)
dfPeru <- ne_states(country = "peru", returnclass = "sf") %>% 
  mutate_at("name", ~ stringi::stri_trans_general(., "latin-ASCII") %>% 
              str_to_upper()) %>%  
  # filter(name != "LIMA PROVINCE") %>%
  mutate(name = recode(name,
                       "LIMA" = "LIMA METROPOLITANA", 
                       "LIMA PROVINCE" = "LIMA PROVINCIAS")) %>%
  rename("DEPARTAMENTO" = "name")



```

```{r global-descarga-data-lake, include=FALSE}
# path_lake <- "HATUN-ANALYTICS-CONSULTING-GROUP/PROJECTS/COVID19/"
# dfRecuentoPositivosDepDist <- load_data(datalake = datalake_name, 
#                                         path = paste0(path_lake, 
#                                                       "dfRecuentoPositivosDepDist"), 
#                                         auth_token = token, 
#                                         sep = ",")
# 
# dfPositivosFechas <- load_data(datalake = datalake_name,
#                                path = paste0(path_lake,
#                                              "dfPositivosFechas"),
#                                auth_token = token, 
#                                sep = ",") %>% 
#   mutate_all(ymd)
# 
# dfRecuentoPositivosPruebas <- load_data(datalake = datalake_name, 
#                                         path = paste0(path_lake, 
#                                                       "dfRecuentoPositivosPruebas"), 
#                                         auth_token = token, 
#                                         sep = ",")
# 
# dfRecuentoPositivosSexo <- load_data(datalake = datalake_name, 
#                                      path = paste0(path_lake, 
#                                                    "dfRecuentoPositivosSexo"), 
#                                      auth_token = token, 
#                                      sep = ",")
# dfConteoConfirmados <- load_data(datalake = datalake_name, 
#                                  path = paste0(path_lake, 
#                                                "tblConteoConfirmados"), 
#                                  auth_token = token, 
#                                  sep = ",")
# dfConteoFallecidos <- load_data(datalake = datalake_name, 
#                                  path = paste0(path_lake, 
#                                                "tblConteoFallecidos"), 
#                                  auth_token = token, 
#                                  sep = ",")
# dfConteoVacunados <- load_data(datalake = datalake_name, 
#                                  path = paste0(path_lake, 
#                                                "tblConteoVacunados"), 
#                                  auth_token = token, 
#                                  sep = ",")
# 
# dfDepartamentoCasos <- list(dfConteoConfirmados, 
#                             dfConteoFallecidos, 
#                             dfConteoVacunados) %>% 
#   reduce(left_join, by = "DEPARTAMENTO") %>% 
#   pivot_longer(cols = -DEPARTAMENTO, 
#                names_to = "casos", 
#                values_to = "cantidad")
```

```{r global-transformacion-data}
dfPositivosFechas <- tibble(MIN_FECHA_RESULTADO = min(dfPositivos$FECHA_RESULTADO,  
                                                      na.rm = TRUE), 
                            MAX_FECHA_RESULTADO = max(dfPositivos$FECHA_RESULTADO, 
                                                      na.rm = TRUE))
dfRecuentoPositivosSexo <- dfPositivos %>% 
  count(SEXO) %>% 
  filter(!is.na(SEXO))

dfRecuentoPositivosDepDist <- dfPositivos %>% 
  count(DEPARTAMENTO, DISTRITO)

dfRecuentoPositivosPruebas <- dfPositivos %>% 
  count(METODODX)

dfConteoConfirmados <- dfPositivos %>% 
  count(DEPARTAMENTO, name = "CONFIRMADOS")

dfConteoFallecidos <- dfFallecidos %>% 
  count(DEPARTAMENTO, name = "FALLECIDOS")

dfConteoVacunados <- dfVacunados %>% 
  count(DEPARTAMENTO, name = "VACUNADOS")

dfDepartamentoCasos <- list(dfConteoConfirmados, dfConteoFallecidos, 
                            dfConteoVacunados) %>% 
  reduce(left_join, by = "DEPARTAMENTO") %>% 
  pivot_longer(cols = -DEPARTAMENTO, 
               names_to = "casos", 
               values_to = "cantidad")
```

# Mapa

```{r}
dfMapPeruCasos <- dfPeru %>% 
  left_join(dfConteoConfirmados %>% 
              mutate_at(vars(DEPARTAMENTO), str_to_upper) %>% 
              mutate(DEPARTAMENTO = recode(DEPARTAMENTO, 
                                           "LIMA REGION" = "LIMA PROVINCIAS", 
                                           "LIMA" = "LIMA METROPOLITANA")), by = "DEPARTAMENTO") 
```

```{r preparacion-data-popup-mapa}
dfPopUp <- dfDepartamentoCasos %>% 
  mutate_at(vars(casos), str_to_title) %>% 
  rename_all(str_to_title) %>% 
  mutate_at(vars(Cantidad), ~ scales::comma(., accuracy = 1)) %>% 
  nest(data = c(Casos, Cantidad)) %>% 
  group_by(Departamento) %>% 
  mutate(pop_up = knitr::kable(data, caption = Departamento[1], format = "html")) %>% 
  ungroup() %>% 
  select(Departamento, pop_up) %>% 
  mutate_at(vars(Departamento), str_to_upper)
  
dfMapPeruCasos <- dfMapPeruCasos %>% 
  dplyr::select(DEPARTAMENTO, latitude, longitude, CONFIRMADOS) %>% 
  mutate(DEPARTAMENTO = recode(DEPARTAMENTO, 
                               "LIMA PROVINCIAS" = "LIMA", 
                               "LIMA METROPOLITANA" = "LIMA")) %>% 
  left_join(dfPopUp %>% rename(DEPARTAMENTO = Departamento), by = "DEPARTAMENTO")
```

```{r objetos de configuracion de mapa}
labels <- sprintf(
  "<strong>%s</strong><br/>%g casos confirmados",
  dfMapPeruCasos$DEPARTAMENTO, dfMapPeruCasos$CONFIRMADOS
  ) %>% 
  lapply(htmltools::HTML)

bins <- c(0, quantile(dfMapPeruCasos$CONFIRMADOS, 
                      probs = seq(0,1,0.125)) %>% 
            .[2:length(.)] %>% 
            as.numeric()) %>% 
  DescTools::RoundTo(50, FUN = ceiling) %>% 
  unique()

pal <- colorBin("YlOrRd", domain = dfMapPeruCasos$CONFIRMADOS, bins = bins)

## Para Clusteres

# coor <- sf::st_set_geometry(dfMapPeruCasos %>% 
#                               dplyr::select(DEPARTAMENTO, latitude, 
#                                             longitude, CONFIRMADOS), NULL)
# 
# coor <- coor %>% 
#   rename(latitud = latitude, 
#          longitud = longitude) %>% 
#   rename_all(str_to_title)
# 
# coor <- coor %>% rename(Cantidad = Confirmados)
# 
# coor <- coor %>% 
#   group_by(Departamento, Longitud, Latitud) %>% 
#   expand(Cantidad = 1:Cantidad) %>% 
#   select(-Cantidad) %>% 
#   ungroup()

## Título
library(htmltools)
library(htmlwidgets)

tag.map.title <- tags$style(HTML("
  .leaflet-control.map-title { 
    transform: translate(-50%,20%);
    position: fixed !important;
    left: 15%; 
    bottom: 3%;
    text-align: left;
    padding-left: 10px; 
    padding-right: 10px; 
    background: rgba(255,255,255,0.75);
    font-weight: bold;
    font-size: 11px;
  }
"))

title <- tags$div(
  tag.map.title, HTML("Agradecimientos por la actualización a: Wilder Buleje Calderón ")
) 

```

```{r renderizado de mapa}
renderLeaflet({
    dfMapPeruCasos %>% 
    dplyr::select(DEPARTAMENTO, latitude, longitude, CONFIRMADOS, pop_up) %>% 
    leaflet(options = leafletOptions(attributionControl = FALSE)) %>%
    addTiles() %>% 
    setView(lng = -76,lat = -9.8,zoom = 5) %>% 
    # addCircleMarkers(data = coor,
    #                  lng = ~ Longitud,
    #                  lat = ~Latitud) %>% 
    # addMarkers(data = coor, 
    #            lng = ~Longitud, 
    #            lat = ~Latitud, clusterOptions = markerClusterOptions()) %>% 
    addPolygons(fillColor = ~pal(CONFIRMADOS), 
                color = "#949191", 
                weight = 3,
                dashArray = 3,
                fillOpacity = 0.8, 
                popup = ~pop_up, 
                label = ~DEPARTAMENTO, 
                labelOptions = labelOptions(
                  textsize = '15px',
                  style = list("font-weight" = "normal", padding = "3px 8px"),
                  direction = "auto"
                ),
                # highlight = highlightOptions(
                #   weight = 5,
                #   color = "#666",
                #   dashArray = "",
                #   fillOpacity = 0.7,
                #   bringToFront = T)
                ) %>% 
    # addControl(title, position = "topright", className = "map-title") %>% 
    # addLegend(pal = pal, 
    #           values = ~CONFIRMADOS, 
    #           opacity = 0.8, title = "Nro. de Casos Confirmados") %>% 
    setMapWidgetStyle(list(background = "white"))
})
```

# Tabla de Casos Confirmados - Nacional

```{r}
DT::renderDT({
  dfRecuentoPositivosDepDist %>% 
    DT::datatable(filter = "top", escape = FALSE, 
                  options = list(sDom  = '<"top">lrt<"bottom">ip', 
                                 pageLength = 20, scrollY = "330px", 
                                 initComplete = JS(
                                   "function(settings, json){", 
                                   "$('body').css({'font-family': 'Trebuchet MS'});", 
                                   "}"
                                 )))}, 
  options = list(scrollX = TRUE))

```

# Porcentaje de Casos {data-orientation=rows}

## Row

### Casos Activos, Recuperados y Fallecidos (A.R.F.)

```{r}
# renderPlot({
#     dfCovidNacional %>%
#     filter(fecha == max(dfCovidNacional$fecha)) %>%
#     select(contains(c("fecha", "acum")), -contains(c("conf", "hosp",
#                                                      "prueb", "uci"))) %>%
#     gather(key = "tipo_caso",
#            value = "cantidad",
#            -fecha) %>%
#     mutate(tipo_caso = recode(tipo_caso,
#                               "recuperados_acum" = "Recuperados",
#                               "muertes_acum" = "Fallecidos",
#                               "activos_acum" = "Activos"),
#            prop = cantidad/sum(cantidad),
#            texto = paste(scales::comma(cantidad),
#                         scales::percent(prop, 1),
#                         sep = "\n"),
#            posy = cumsum(prop) - 0.5*prop) %>%
#     mutate(tipo_caso = fct_reorder(tipo_caso, cantidad)) %>%
#     {
#         ggplot(., aes(x = "", y = prop, fill = tipo_caso)) +
#             geom_col() +
#             geom_text(aes(label = texto, family = "Trebuchet MS"),
#                       color = "white",
#                       size = 5,
#                       position = position_stack(vjust = 0.5)) +
#             scale_y_continuous(labels = scales::comma_format()) +
#             scale_fill_manual(values=c("#CC6666", "#9999CC", "#66CC99")) +
#             coord_polar(theta = "y", start = pi/2) +
#             theme_void() +
#             labs(
#                 title = "Casos Activos, Recuperados y\nFallecidos por COVID-19 en Perú",
#                 subtitle = paste("Actualizado hasta",
#                                  day(.$fecha[1]),
#                                  "de",
#                                  meses[month(.$fecha[1])],
#                                  "del",
#                                  year(.$fecha[1])),
#                 caption = "Fuente: Instituto Nacional de Salud y Centro Nacional de\nEpidemiología,prevención y Control de Enfermedades\nMINSA",
#                 fill = "Caso: "
#                  ) +
#             theme(text = element_text(family = "Trebuchet MS"),
#                   plot.caption = element_text(face = "bold",
#                                               size = 10,
#                                               hjust = 0),
#                   plot.title = element_text(face = "bold",
#                                             size = 16),
#                   legend.title = element_text(size = 13),
#                   legend.text = element_text(size = 12),
#                   plot.subtitle = element_text(size = 14),
#                   legend.position = "bottom")
#     }
# })
```

```{r}
tbFechaCovidNacional <- dfCovidNacional %>% 
  filter(fecha == max(dfCovidNacional$fecha)) %>% 
  select(fecha)

renderHighchart({
  dfCovidNacional %>% 
    filter(fecha == max(dfCovidNacional$fecha)) %>% 
    select(contains(c("fecha", "acum")), -contains(c("conf", "hosp", 
                                                     "prueb", "uci"))) %>% 
    gather(key = "tipo_caso", 
           value = "cantidad", 
           -fecha) %>% 
    mutate(tipo_caso = recode(tipo_caso, 
                              "recuperados_acum" = "Recuperados", 
                              "muertes_acum" = "Fallecidos", 
                              "activos_acum" = "Activos"), 
           prop = cantidad/sum(cantidad), 
           texto = glue("Cantidad: {scales::comma(cantidad)}<br>
                        Porcentaje: {scales::percent(prop)}"), 
           color = case_when(
             tipo_caso == "Fallecidos" ~ "#CC6666", 
             tipo_caso == "Activos" ~ "#9999CC", 
             tipo_caso == "Recuperados" ~ "#66CC99"
           )) %>%
    hchart(
      "pie",
      hcaes(x = tipo_caso, y = prop, color = color), 
      tooltip = list(pointFormat = "{point.texto}"), 
      innerSize = "50%",
      dataLabels = list(alignTo = "connectors")
    ) %>%
    hc_title(text = "Casos Activos, Recuperados y Fallecidos por COVID-19", 
             bold = TRUE) %>%
    hc_subtitle(text = paste("Actualizado hasta",
                                 day(tbFechaCovidNacional$fecha[1]),
                                 "de",
                                 meses[month(tbFechaCovidNacional$fecha[1])],
                                 "del",
                                 year(tbFechaCovidNacional$fecha[1]))) %>% 
    hc_plotOptions(series = list(animation = FALSE)) %>% 
    hc_exporting(enabled = TRUE, 
                 buttons = list(
                   contextButton = list(
                     menuItems = c("downloadPNG", "downloadSVG")
                 ))) %>% 
    # hc_size(height = 270, width = 550) %>% 
    highcharter::hc_tooltip(crosshairs = TRUE, 
                            useHTML = TRUE, 
                            shared = TRUE, 
                            headerFormat = '<span style="font-size: 15px;">{point.key}</span><br/>', 
                            style = list(fontWeight = "bold", 
                                         fontSize = "13px", 
                                         family = "Trebuchet MS")) %>% 
    hc_add_theme(hc_theme_elementary())
})
```


### Género

```{r}
# renderPlot({
#     dfRecuentoPositivosSexo %>% 
#     na.omit() %>% 
#     mutate(prop = n/sum(n), 
#            posy = cumsum(prop) - 0.5*prop, 
#            texto = paste(scales::comma(n, 1), 
#                          scales::percent(prop, 0.1), sep = "\n")) %>% 
#     ggplot(aes("", prop, fill = SEXO)) + 
#     geom_col() + 
#     geom_text(aes(label = texto, family = "Trebuchet MS"), 
#               color = "white", 
#               size = 5, 
#               position = position_stack(0.5)) + 
#     coord_polar(theta = "y", start = 0) + 
#     labs(title = "Casos Confirmados de COVID - 19\nsegún Sexo", 
#          subtitle = paste("Actualizado hasta", 
#                           day(dfPositivosFechas$MAX_FECHA_RESULTADO), 
#                           "de", 
#                           meses[month(dfPositivosFechas$MAX_FECHA_RESULTADO)], 
#                           "del", 
#                           year(dfPositivosFechas$MAX_FECHA_RESULTADO)), 
#          fill = "Sexo:", 
#          caption = "Fuente: Instituto Nacional de Salud y Centro Nacional de\nEpidemiologia,prevención y Control de Enfermedades\nMINSA") + 
#     theme_void() + 
#     scale_fill_manual(values = c("#ff9999", "#0072b2")) + 
#     theme(text = element_text(family = "Trebuchet MS"),
#           plot.caption = element_text(face = "bold", 
#                                       size = 10, 
#                                       hjust = 0),
#           plot.title = element_text(face = "bold", 
#                                     size = 16), 
#           legend.title = element_text(size = 13), 
#           legend.text = element_text(size = 12), 
#           plot.subtitle = element_text(size = 14), 
#           legend.position = "bottom")
# })
```

```{r}
renderHighchart({
  dfRecuentoPositivosSexo %>% 
    mutate(prop = n / sum(n),
           texto = glue("Cantidad: {scales::comma(n)}<br> 
                        Porcentaje: {scales::percent(prop)}"), 
           color = case_when(
             SEXO == "Masculino" ~ "#0072b2", 
             SEXO == "Femenino" ~ "#ff9999"
           )) %>%
    hchart(
      "pie",
      hcaes(x = SEXO, y = prop, color = color),
      tooltip = list(pointFormat = "{point.texto}"), 
      innerSize = "50%", 
      dataLabels = list(alignTo = "connectors")
    ) %>%
    hc_title(text = "Casos Confirmados de COVID - 19 según Sexo", 
             bold = TRUE) %>% 
    hc_subtitle(text = paste("Actualizado hasta",
                          day(dfPositivosFechas$MAX_FECHA_RESULTADO),
                          "de",
                          meses[month(dfPositivosFechas$MAX_FECHA_RESULTADO)],
                          "del",
                          year(dfPositivosFechas$MAX_FECHA_RESULTADO))) %>% 
    hc_plotOptions(series = list(animation = FALSE)) %>% 
    # hc_size(height = 270, width = 550) %>% 
    hc_exporting(enabled = TRUE, 
                 buttons = list(
                   contextButton = list(
                     menuItems = c("downloadPNG", "downloadSVG")
                 ))) %>% 
    highcharter::hc_tooltip(crosshairs = TRUE, 
                            useHTML = TRUE, 
                            shared = TRUE,
                            headerFormat = '<span style="font-size: 15px;">{point.key}</span><br/>', 
                            style = list(fontWeight = "bold", 
                                         fontSize = "13px", 
                                         family = "Trebuchet MS")) %>% 
    hc_add_theme(hc_theme_elementary())
})

# highchartOutput("casosSexo", width = "600px")

```

### Pruebas Realizadas

```{r}
# renderPlot({
#     dfRecuentoPositivosPruebas %>% 
#     mutate(prop = n/sum(n), 
#            posy = cumsum(prop)- 0.5*prop, 
#            texto = paste(scales::comma(n), scales::percent(prop), sep = "\n")) %>% 
#     ggplot(aes("", prop, fill = METODODX)) + 
#     geom_col() + 
#     theme_void() + 
#     coord_polar(theta = "y", start = pi/2) + 
#     geom_text(aes(label = texto, family = "Trebuchet MS"), 
#               color = "white", 
#               size = 5, 
#               position = position_stack(0.5)) + 
#     labs(title = "Uso de Pruebas Moleculares y Rápidas", 
#          subtitle = paste("Actualizado hasta", 
#                           day(dfPositivosFechas$MAX_FECHA_RESULTADO), 
#                           "de", 
#                           meses[month(dfPositivosFechas$MAX_FECHA_RESULTADO)], 
#                           "del", 
#                           year(dfPositivosFechas$MAX_FECHA_RESULTADO)), 
#          fill = "Tipo prueba:", 
#          caption = "Fuente: Instituto Nacional de Salud y Centro Nacional de\nEpidemiología,prevención y Control de Enfermedades\nMINSA") + 
#     scale_fill_manual(labels = c("Pr" = "Prueba\nrápida", 
#                                  "Pcr" = "Prueba\nmolecular", 
#                                  "Ag" = "Prueba\nantígenos"), 
#                         values = c("#1b9e77", 
#                                    "#d95f02", 
#                                    "#7570b3")) + 
#     theme(text = element_text(family = "Trebuchet MS"),
#           plot.caption = element_text(face = "bold",
#                                       size = 10,
#                                       hjust = 0),
#           plot.title = element_text(face = "bold",
#                                     size = 16),
#           legend.title = element_text(size = 13),
#           legend.text = element_text(size = 12),
#           plot.subtitle = element_text(size = 14),
#           legend.position = "bottom")
# })
```

```{r}
renderHighchart({
  dfRecuentoPositivosPruebas %>% 
    mutate(prop = n/sum(n), 
           posy = cumsum(prop)- 0.5*prop, 
           texto = glue("Cantidad: {scales::comma(n)}<br> 
                        Porcentaje: {scales::percent(prop)}"), 
           color = case_when(
             METODODX == "Ag" ~ "#1b9e77", 
             METODODX == "Pcr" ~ "#d95f02", 
             METODODX == "Pr" ~ "#7570b3"
           ), 
           METODODX = recode(METODODX, 
                             "Ag" = "Prueba\nantígenos", 
                             "Pcr" = "Prueba\nmolecular", 
                             "Pr" = "Prueba\nrápida")) %>% 
  hchart(
      "pie",
      hcaes(x = METODODX, y = prop, color = color),
      tooltip = list(pointFormat = "{point.texto}"), 
      innerSize = "50%", 
      dataLabels = list(alignTo = "connectors")
    ) %>%
  hc_title(text = "Uso de Pruebas Moleculares y Rápidas", 
           bold = TRUE) %>% 
  hc_subtitle(text = paste("Actualizado hasta",
                          day(dfPositivosFechas$MAX_FECHA_RESULTADO),
                          "de",
                          meses[month(dfPositivosFechas$MAX_FECHA_RESULTADO)],
                          "del",
                          year(dfPositivosFechas$MAX_FECHA_RESULTADO))) %>% 
  hc_plotOptions(series = list(animation = FALSE)) %>% 
  hc_exporting(enabled = TRUE, 
               buttons = list(
                 contextButton = list(
                   menuItems = c("downloadPNG", "downloadSVG")
                   ))) %>% 
  # hc_size(height = 270, width = 550) %>% 
  highcharter::hc_tooltip(crosshairs = TRUE, 
                          useHTML = TRUE, 
                          shared = TRUE,
                          headerFormat = '<span style="font-size: 15px;">{point.key}</span><br/>', 
                          style = list(fontWeight = "bold", 
                                       fontSize = "13px", 
                                       family = "Trebuchet MS")) %>% 
  hc_add_theme(hc_theme_elementary())
})
```

# Seguimiento en el Tiempo

## Column {.tabset}

### Acumulación Diaria - Casos Confirmados

```{r}
library(plotly)
# tsCasosConfirmadosAcum <- dfCovidNacional %>% 
#   select(contains(c("fecha", "confirmados_acum"))) %>% 
#   mutate(texto = paste0("Fecha: ", fecha, "\n", 
#                        "Cantidad: ", scales::comma(confirmados_acum, 1))) %>% 
#   ggplot(aes(fecha, confirmados_acum, 
#              group = 1, 
#              text = texto)) + 
#   geom_line(col = "#97293f") + 
#   # geom_point(col = "#97293f") + 
#   scale_y_continuous("Cantidad", labels = scales::comma_format()) + 
#   scale_x_date("Fecha")
```

```{r}
# plotly::renderPlotly({
#   plotly::ggplotly(tsCasosConfirmadosAcum, tooltip = "text") %>% 
#     plotly::layout(
#       title = list(
#         text = paste0("COVID-19 Perú: Acumulación Diaria de Casos Confirmados", 
#                       "<br>",
#                       "<sup>", 
#                       paste("Actualizado hasta", 
#                             day(max(dfCovidNacional$fecha, na.rm = T)),
#                             "de",
#                             meses[month(max(dfCovidNacional$fecha, na.rm = T))],
#                             "del",
#                             year(max(dfCovidNacional$fecha, na.rm = T))),
#                       "</sup>"), 
#         y = 0.95), 
#       xaxis = list(fixedrange = TRUE), 
#       yaxis = list(fixedrange = TRUE)
#     )
# })
```

```{r}
renderHighchart({
  dfCovidNacional %>% 
    select(contains(c("fecha", "confirmados_acum"))) %>% 
    hchart(type = "line", 
           hcaes(x = fecha, y = confirmados_acum), 
           name = "Confirmados", 
           color = "#97293f") %>% 
    hc_exporting(enabled = TRUE, 
                 buttons = list(
                   contextButton = list(
                     menuItems = c("downloadPNG", "downloadSVG", "downloadCSV", 
                                   "downloadXLS")
                     )
                   )) %>% 
    hc_title(text = "Acumulación Diaria de Casos Confirmados") %>% 
    hc_subtitle(text = paste("Actualizado hasta",
                             day(max(dfCovidNacional$fecha, na.rm = T)),
                             "de",
                             meses[month(max(dfCovidNacional$fecha, na.rm = T))],
                             "del",
                             year(max(dfCovidNacional$fecha, na.rm = T)))) %>% 
    hc_yAxis(title = list(text = "Número de Personas")) %>% 
    hc_xAxis(title = list(text = "Fecha"))
  })
```


### Variación Diaria - Casos Confirmados

```{r}
# tsCasosConfirmados <- dfCovidNacional %>% 
#   select(contains(c("fecha", "confirmados")), 
#          -contains("acum")) %>% 
#   mutate_if(is.numeric, ~ replace_na(., 0)) %>% 
#   mutate(texto = paste0("Fecha: ", fecha, "\n", 
#                         "Cantidad: ", scales::comma(confirmados_nuevos, 1))) %>% 
#   ggplot(aes(fecha, 
#              confirmados_nuevos,  
#              text = texto, 
#              group = 1)) + 
#   geom_line(color = "#97293f") + 
#   # geom_point(color = "#97293f") + 
#   scale_y_continuous(labels = scales::comma_format()) + 
#   labs(y = "Cantidad", 
#        x = "Fecha")


```

```{r renderizado de grafico de secuencias de casos confirmados diarios}
# renderPlotly({
#     ggplotly(tsCasosConfirmados, tooltip = "text") %>%
#         layout(
#             title = list(
#               text = paste0("COVID-19 Perú: Variación Diaria de Casos Confirmados",
#                             "<br>",
#                             "<sup>",
#                             paste("Actualizado hasta", 
#                                   day(max(dfCovidNacional$fecha, na.rm = T)),
#                                   "de",
#                                   meses[month(max(dfCovidNacional$fecha, na.rm = T))],
#                                   "del",
#                                   year(max(dfCovidNacional$fecha, na.rm = T))),
#                             "</sup>"), 
#               y = 0.95), 
#            xaxis = list(fixedrange = TRUE), 
#            yaxis = list(fixedrange = TRUE)
#         )
# })
```

```{r}
renderHighchart({
  dfCovidNacional %>% 
    select(contains(c("fecha", "confirmados")), 
           -contains("acum")) %>% 
    mutate_if(is.numeric, ~ replace_na(., 0)) %>% 
    hchart(type = "line", 
           hcaes(x = fecha, y = confirmados_nuevos), 
           color = "#97293f", 
           name = "Confirmados") %>% 
    hc_title(text = "Variación Diaria de Casos Confirmados") %>% 
    hc_subtitle(text = paste("Actualizado hasta",
                             day(max(dfCovidNacional$fecha, na.rm = T)),
                             "de",
                             meses[month(max(dfCovidNacional$fecha, na.rm = T))],
                             "del",
                             year(max(dfCovidNacional$fecha, na.rm = T)))) %>% 
    hc_yAxis(title = list(text = "Número de Personas")) %>% 
    hc_xAxis(title = list(text = "Fecha")) %>% 
    hc_exporting(enabled = TRUE, 
                 buttons = list(
                   contextButton = list(
                     menuItems = c("downloadPNG", "downloadSVG", "downloadCSV", 
                                   "downloadXLS")
                     )
                   ))
})
```

### Acumulación Diaria - Casos A.R.F

```{r}
# tsCasosAcum <- dfCovidNacional %>% 
#   select(contains(c("fecha", "acum")), -contains(c("confirmados", 
#                                                    "pruebas", "uci", "hosp"))) %>% 
#   mutate_if(is.numeric, ~ replace_na(., 0)) %>% 
#   gather(key = "Caso", 
#          value = "Valor", 
#          -fecha) %>% 
#   mutate(Caso = recode(Caso, 
#                        "activos_acum" = "Activos", 
#                        "recuperados_acum" = "Recuperados", 
#                        "muertes_acum" = "Fallecidos"), 
#          texto = paste0("Fecha: ", fecha, "\n", 
#                         "Caso: ", Caso, "\n", 
#                         "Cantidad: ", scales::comma(Valor, 1))) %>% 
#   ggplot(aes(fecha, 
#              Valor, 
#              color = Caso, 
#              text = texto, 
#              group = Caso)) + 
#   geom_line() + 
#   # geom_point() + 
#   scale_y_continuous(labels = scales::comma_format()) + 
#   scale_color_manual(values = c("#9999CC", "#CC6666", "#66CC99")) + 
#   labs(y = "Cantidad", 
#        x = "Fecha", 
#        color = "Tipo de Caso: ")
```

```{r renderizado de grafico de secuencias de casos acumulados diarios ARM}
# renderPlotly({
#     ggplotly(tsCasosAcum, tooltip = "text") %>%
#         layout(
#             legend = list(
#                 orientation = "h",
#                 xanchor = "center",
#                 x = 0.5,
#                 y = -0.2
#             ),
#             title = list(
#               text = paste0("COVID-19 Perú: Acumulación Diaria de Casos Activos, Recuperados y Fallecidos", 
#                             "<br>",
#                             "<sup>",
#                             paste("Actualizado hasta", 
#                                   day(max(dfCovidNacional$fecha, na.rm = T)), 
#                                   "de",
#                                   meses[month(max(dfCovidNacional$fecha, na.rm = T))],
#                                   "del",
#                                   year(max(dfCovidNacional$fecha, na.rm = T))),
#                             "</sup>"), 
#               y = 0.95), 
#             xaxis = list(fixedrange = TRUE), 
#             yaxis = list(fixedrange = TRUE), 
#             annotations = list(x = 0.03, 
#                                y = 0.9, 
#                                text = "Nota: El 23 de julio del 2020,\nMINSA sincera cifras de\nfallecidos por COVID-19", 
#                                showarrow = FALSE, 
#                                xref = "paper", 
#                                yref = "paper", 
#                                xanchor = "left", 
#                                yanchor = "center", 
#                                xshift = 0, 
#                                yshift = 0, 
#                                font = list(size = 10))
#         )
# })
```

```{r}
renderHighchart({
  dfCovidNacional %>% 
    select(contains(c("fecha", "acum")), -contains(c("confirmados", 
                                                     "pruebas", "uci", "hosp"))) %>% 
    mutate_if(is.numeric, ~ replace_na(., 0)) %>% 
    gather(key = "Caso",
           value = "Valor", 
           -fecha) %>%
    mutate(Caso = recode(Caso, 
                         "activos_acum" = "Activos", 
                         "recuperados_acum" = "Recuperados", 
                         "muertes_acum" = "Fallecidos"), 
         color = case_when(
           Caso == "Recuperados" ~ "#66cc99",
           Caso == "Activos" ~ "#9999cc", 
           Caso == "Fallecidos" ~ "#cc6666"
         )) %>% 
  hchart(type = "line", 
         hcaes(fecha, Valor, group = Caso)) %>% 
  hc_colors(c("#9999cc", "#cc6666", "#66cc99")) %>% 
  hc_exporting(enabled = TRUE, 
                 buttons = list(
                   contextButton = list(
                     menuItems = c("downloadPNG", "downloadSVG", "downloadCSV", 
                                   "downloadXLS")
                     )
                   )) %>% 
  hc_title(text = "Acumulación Diaria de Casos Activos, Recuperados y Fallecidos") %>% 
  hc_subtitle(text = paste("Actualizado hasta", 
                           day(max(dfCovidNacional$fecha, na.rm = T)), 
                           "de",
                           meses[month(max(dfCovidNacional$fecha, na.rm = T))],
                           "del",
                           year(max(dfCovidNacional$fecha, na.rm = T)))) %>% 
  hc_yAxis(title = list(text = "Número de Personas")) %>% 
  hc_xAxis(title = list(text = "Fecha")) %>% 
  hc_tooltip(enabled = TRUE, 
             crosshairs = TRUE, 
             shared = TRUE)
})
```

### Variación Diaria - Casos A.R.F.

```{r}
# tsCasosNuevos <- dfCovidNacional %>% 
#   select(contains(c("fecha", "nuevos")), 
#          -contains(c("confirmados", "uci", "hosp", "prueb"))) %>% 
#   mutate_if(is.numeric, ~ replace_na(., 0)) %>% 
#   gather(key = "Caso", 
#          value = "Valor", 
#          -fecha) %>% 
#   mutate(Caso = recode(Caso, 
#                        "activos_nuevos" = "Activos", 
#                        "recuperados_nuevos" = "Recuperados", 
#                        "muertes_nuevos" = "Fallecidos"), 
#          texto = paste0("Fecha: ", fecha, "\n", 
#                         "Caso: ", Caso, "\n", 
#                         "Cantidad: ", scales::comma(Valor, 1))) %>% 
#   ggplot(aes(fecha, 
#              Valor, 
#              color = Caso, 
#              text = texto, 
#              group = Caso)) + 
#   geom_line() + 
#   # geom_point() + 
#   scale_y_continuous(labels = scales::comma_format()) + 
#   scale_color_manual(values = c("#9999CC", "#CC6666", "#66CC99")) + 
#   labs(y = "Cantidad", 
#        x = "Fecha", 
#        color = "Tipo de Caso: ") + 
#   theme(legend.position = "bottom")
```

```{r renderizando grafico de secuencias de casos nuevos ARM}
# renderPlotly({
#   plotly::ggplotly(tsCasosNuevos, tooltip = "text") %>% 
#     plotly::config(displayModeBar = FALSE) %>%
#     layout(title = list(
#       text = paste0("COVID-19 Perú: Variación Diaria de Casos Activos, Recuperados y Fallecidos", 
#                     "<br>", 
#                     "<sup>", 
#                     paste("Actualizado hasta", 
#                           day(max(dfCovidNacional$fecha, na.rm = T)), 
#                           "de", 
#                           meses[month(max(dfCovidNacional$fecha, na.rm = T))], 
#                           "del", 
#                           year(max(dfCovidNacional$fecha, na.rm = T))), 
#                     "</sup>"), 
#       y = 0.95), 
#       legend = list(orientation = "h", 
#                     xanchor = "center", 
#                     x = 0.5, 
#                     y = -0.2), 
#       xaxis = list(fixedrange = TRUE), 
#       yaxis = list(fixedrange = TRUE), 
#       annotations = list(x = 0.03, 
#                          y = 0.9, 
#                          text = "Nota: El 23 de julio del 2020,\nMINSA sincera cifras de\nfallecidos por COVID-19", 
#                          showarrow = FALSE, 
#                          xref = "paper", 
#                          yref = "paper", 
#                          xanchor = "left", 
#                          yanchor = "center", 
#                          xshift = 0, 
#                          yshift = 0, 
#                          font = list(size = 10))) 
# })
```

```{r}
renderHighchart({
  dfCovidNacional %>% 
    select(contains(c("fecha", "nuevos")), 
           -contains(c("confirmados", "uci", "hosp", "prueb"))) %>% 
    mutate_if(is.numeric, ~ replace_na(., 0)) %>% 
    gather(key = "Caso", 
           value = "Valor", 
           -fecha) %>% 
    mutate(Caso = recode(Caso, 
                         "activos_nuevos" = "Activos", 
                         "recuperados_nuevos" = "Recuperados", 
                         "muertes_nuevos" = "Fallecidos")) %>% 
    hchart(type = "line", 
           hcaes(fecha, Valor, group = Caso)) %>% 
    hc_colors(c("#9999cc", "#cc6666", "#66cc99")) %>% 
    hc_exporting(enabled = TRUE, 
                 buttons = list(
                   contextButton = list(
                     menuItems = c("downloadPNG", "downloadSVG", "downloadCSV", 
                                   "downloadXLS")
                     )
                   )) %>% 
    hc_title(text = "Variación Diaria de Casos Activos, Recuperados y Fallecidos") %>% 
    hc_subtitle(text = paste("Actualizado hasta", 
                             day(max(dfCovidNacional$fecha, na.rm = T)), 
                             "de",
                             meses[month(max(dfCovidNacional$fecha, na.rm = T))],
                             "del",
                             year(max(dfCovidNacional$fecha, na.rm = T)))) %>% 
    hc_yAxis(title = list(text = "Número de Personas")) %>% 
    hc_xAxis(title = list(text = "Fecha")) %>% 
    hc_tooltip(enabled = TRUE, 
               crosshairs = TRUE, 
               shared = TRUE)
})
```

